name: build-branch
on:
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    uses: OKA-Global/ozo-tech-workflows/.github/workflows/lint-and-test.yml@main
    with:
      node-version: "18.x"
      bitrise: true
      bitrise_target_branch: ${{ github.head_ref }}
    secrets:
      publish_token: ${{ secrets.GITHUB_TOKEN }}
      bitrise_app_id: ${{ secrets.BITRISE_APP_ID }}
      bitrise_build_trigger_secret: ${{ secrets.BITRISE_BUILD_TRIGGER_SECRET }}

  build-and-push:
    uses: OKA-Global/ozo-tech-workflows/.github/workflows/build-image.yml@main
    needs: [lint-test]
    permissions:
      packages: write
      contents: read
    with:
      dockerfile_path: ./
      dockerfile_name: Dockerfile
      image_name: ozo-ozogames
      tag: ${{github.head_ref}}
      release: false
      push_image: true
      create_git_tag: false
      pre_build: false
      service: false

  success-message:
    runs-on: ubuntu-latest
    if: success()
    needs: [build-and-push, lint-test]
    steps:
        - uses: actions/checkout@v3
          with:
              fetch-depth: 0
              ref: ${{ github.head_ref }}
        - name: Decorate PR with branch deployment URL
          uses: thollander/actions-comment-pull-request@v1
          with:
              message: |
                  :white_check_mark: Build of ${{ github.head_ref  }}  successful :white_check_mark:
                  Please click [here](https://platform-control.platformservices.io/job/gaming-aws/job/branch-deployment/parambuild/?BRANCH=${{ github.head_ref }}&PR_STATUS=PR_OPENED&REPO_URL=https://github.com/OKA-Global/ozo-ozogames&SLACK_CHANNEL=%23%0Aozogames-bots&SQUAD=ozogames&TF_VERSION=1.0&TERRAFORM_FOLDER=apps/web/terraform/) to deploy branch to test
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  fail-message:
      runs-on: ubuntu-latest
      if: failure()
      needs: [build-and-push, lint-test]
      steps:
          - uses: actions/checkout@v3
            with:
                fetch-depth: 0
                ref: ${{ github.head_ref }}
          - name: Decorate PR with failed build info
            uses: thollander/actions-comment-pull-request@v1
            with:
                message: |
                    :red-circle: Build of ${{ github.head_ref }} fail :red-circle:
                    Please click [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) to see failure
                GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
